"use client";

import { useEffect, useRef } from "react";
import {
  DESTINATIONS,
  HOME_PORT,
  SHIP_PATH,
  SHIP_VIEWBOX,
  project,
  type Port,
  type WorldMapData,
} from "@/lib/world";
import { useIsCoarsePointer, usePrefersReducedMotion } from "@/lib/hooks";

/**
 * Animated world map for the hero background.
 *
 * Canvas 2D rather than SVG or WebGL: the camera pans and zooms every frame, so
 * a DOM tree of 199 country paths would thrash layout, while WebGL would add a
 * context plus a large runtime on top of the page's existing backdrop-filter
 * cost. Geometry comes from public/world-map.json (generated by
 * `npm run build:map`) — 14.8k points, 41 KB gzipped.
 *
 * Each voyage runs a five-phase cycle: fly home, focus the home port, sail a
 * bowed route while the camera follows, confirm arrival with a check mark,
 * clear.
 *
 * Performance: measured at 25 ms/frame before tuning, on a fast machine. The
 * budget is dominated by fill rate, so the device tier below scales the canvas
 * resolution first, then the per-frame path work, then the frame rate itself.
 */

const PHASE = {
  /** Camera flies back from the last destination to the home port. */
  approach: 1500,
  focus: 1500,
  arrive: 1700,
  clear: 900,
} as const;

const TRAVEL_MIN = 4600;
const TRAVEL_MAX = 8200;

const ZOOM_NEAR = 4.2;
const ZOOM_WIDE = 1.45;

/** Camera follow time constant, in ms. Lower = tighter on the ship. */
const CAMERA_TAU = 70;

/**
 * The artwork is a side view whose bow points LEFT: the crane mast sits at the
 * left edge and the tall superstructure — which sits at the stern on a real
 * cargo vessel — at the right. A side view must therefore be *mirrored* to
 * change direction, never rotated past vertical, or the ship sails upside down.
 */
const SHIP_FACES_LEFT = true;
const SHIP_SCREEN_SIZE = 30;
/** Ships stay recognisably upright; routes are near-horizontal anyway. */
const MAX_TILT = 0.52;

/** Canvas cannot resolve CSS custom properties in `font`; use a literal stack. */
const LABEL_FONT = '600 11px ui-sans-serif, system-ui, -apple-system, sans-serif';

type Tier = {
  /** Device-pixel cap. The single largest lever — cost scales with area. */
  dpr: number;
  targetFps: number;
  /** Countries smaller than this on screen are skipped entirely. */
  minFeaturePx: number;
  routeSamples: number;
  /** The ship's second, wider pass that fakes a glow. */
  glow: boolean;
  /** The faint full-length lane drawn under the travelled trail. */
  laneUnderlay: boolean;
};

function detectTier(coarsePointer: boolean): Tier {
  const nav = navigator as Navigator & { deviceMemory?: number };
  const cores = nav.hardwareConcurrency ?? 4;
  const memory = nav.deviceMemory ?? 4;

  if (coarsePointer || cores <= 4 || memory <= 4) {
    return {
      dpr: 1,
      targetFps: 30,
      minFeaturePx: 3.5,
      routeSamples: 70,
      glow: false,
      laneUnderlay: false,
    };
  }
  if (cores <= 8) {
    return {
      dpr: 1.35,
      targetFps: 45,
      minFeaturePx: 2,
      routeSamples: 100,
      glow: true,
      laneUnderlay: true,
    };
  }
  return {
    dpr: 1.75,
    targetFps: 60,
    minFeaturePx: 1.25,
    routeSamples: 140,
    glow: true,
    laneUnderlay: true,
  };
}

type Voyage = {
  from: Port;
  to: Port;
  a: { x: number; y: number };
  b: { x: number; y: number };
  control: { x: number; y: number };
  travelMs: number;
  startedAt: number;
  /** Where the camera was left by the previous voyage; null on the first. */
  cameraFrom: { x: number; y: number } | null;
  /** Precomputed once per voyage — never rebuilt per frame. */
  highlight: Set<string>;
  samples: Float64Array;
};

const easeInOut = (t: number) => (t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2);
const easeOutBack = (t: number) => {
  const c = 1.70158;
  return 1 + (c + 1) * (t - 1) ** 3 + c * (t - 1) ** 2;
};

export function WorldMapCanvas({ className = "" }: { className?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const reducedMotion = usePrefersReducedMotion();
  const coarsePointer = useIsCoarsePointer();

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const context = canvas.getContext("2d", { alpha: true });
    if (!context) return;
    const ctx = context;

    const tier = detectTier(coarsePointer);
    const frameInterval = 1000 / tier.targetFps;

    let cancelled = false;
    let frame = 0;
    let running = false;
    let onScreen = true;

    let width = 0;
    let height = 0;

    let map: WorldMapData | null = null;
    let shapes: { id: string; path: Path2D; box: [number, number, number, number] }[] = [];
    const shipPath = new Path2D(SHIP_PATH);

    let baseScale = 1;
    const camera = { x: 0, y: 0, zoom: ZOOM_WIDE };
    let cameraInitialised = false;

    let voyage: Voyage | null = null;
    let mapAlpha = 0;
    let lastFrame = 0;
    let lastDraw = 0;

    // Scratch buffer for projected route points, allocated once. Rebuilding a
    // 141-element array of objects every frame was the main source of GC churn.
    const screenPoints = new Float64Array((tier.routeSamples + 1) * 2);

    const resize = () => {
      const rect = canvas.getBoundingClientRect();
      width = rect.width;
      height = rect.height;
      const dpr = Math.min(window.devicePixelRatio || 1, tier.dpr);
      canvas.width = Math.round(width * dpr);
      canvas.height = Math.round(height * dpr);
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      if (map) baseScale = Math.max(width / map.width, height / map.height);
    };

    const pick = <T,>(items: T[], not?: T): T => {
      let choice = items[Math.floor(Math.random() * items.length)];
      if (not && items.length > 1) {
        while (choice === not) choice = items[Math.floor(Math.random() * items.length)];
      }
      return choice;
    };

    const makeVoyage = (now: number, previous?: Port): Voyage => {
      const data = map!;
      const to = pick(DESTINATIONS, previous);
      const a = project(HOME_PORT.lat, HOME_PORT.lng, data.width, data.height, data.geo);
      const rawB = project(to.lat, to.lng, data.width, data.height, data.geo);

      // The map's seam falls mid-Pacific, so for many destinations the short way
      // round runs off one edge and back on the other. Pick whichever direction
      // is actually shorter and let b.x fall outside the map; the map itself is
      // tiled horizontally when drawn, so the route stays over real geography.
      const candidates = [rawB.x - a.x, rawB.x - a.x - data.width, rawB.x - a.x + data.width];
      const shortest = candidates.reduce((best, d) => (Math.abs(d) < Math.abs(best) ? d : best));
      const b = { x: a.x + shortest, y: rawB.y };

      const midX = (a.x + b.x) / 2;
      const midY = (a.y + b.y) / 2;
      const dx = b.x - a.x;
      const dy = b.y - a.y;
      const distance = Math.hypot(dx, dy);
      const bow = distance * 0.16;
      const sign = midY > data.height / 2 ? 1 : -1;
      const control = {
        x: midX + (dy / (distance || 1)) * bow * sign,
        y: midY - (dx / (distance || 1)) * bow * sign,
      };

      const travelMs = Math.min(
        TRAVEL_MAX,
        Math.max(TRAVEL_MIN, TRAVEL_MIN + (distance / data.width) * 5200)
      );

      // Sample the curve once here rather than on every frame.
      const count = tier.routeSamples;
      const samples = new Float64Array((count + 1) * 2);
      for (let i = 0; i <= count; i += 1) {
        const t = i / count;
        const inv = 1 - t;
        samples[i * 2] = inv * inv * a.x + 2 * inv * t * control.x + t * t * b.x;
        samples[i * 2 + 1] = inv * inv * a.y + 2 * inv * t * control.y + t * t * b.y;
      }

      return {
        from: HOME_PORT,
        to,
        a,
        b,
        control,
        travelMs,
        startedAt: now,
        cameraFrom: previous
          ? project(previous.lat, previous.lng, data.width, data.height, data.geo)
          : null,
        highlight: new Set([HOME_PORT.country, to.country]),
        samples,
      };
    };

    const bezierX = (v: Voyage, t: number) => {
      const inv = 1 - t;
      return inv * inv * v.a.x + 2 * inv * t * v.control.x + t * t * v.b.x;
    };
    const bezierY = (v: Voyage, t: number) => {
      const inv = 1 - t;
      return inv * inv * v.a.y + 2 * inv * t * v.control.y + t * t * v.b.y;
    };
    const bezierHeading = (v: Voyage, t: number) => {
      const inv = 1 - t;
      const dx = 2 * inv * (v.control.x - v.a.x) + 2 * t * (v.b.x - v.control.x);
      const dy = 2 * inv * (v.control.y - v.a.y) + 2 * t * (v.b.y - v.control.y);
      return Math.atan2(dy, dx);
    };

    const screenX = (x: number) => (x - camera.x) * baseScale * camera.zoom + width / 2;
    const screenY = (y: number) => (y - camera.y) * baseScale * camera.zoom + height / 2;

    const drawMap = (highlight: Set<string>) => {
      const data = map;
      if (!data) return;
      const scale = baseScale * camera.zoom;

      const halfW = width / 2 / scale;
      const halfH = height / 2 / scale;
      const left = camera.x - halfW;
      const right = camera.x + halfW;
      const top = camera.y - halfH;
      const bottom = camera.y + halfH;
      const minSpan = tier.minFeaturePx / scale;

      ctx.lineJoin = "round";

      // Three copies side by side: routes and the camera may run past either
      // edge when a voyage crosses the seam, and the world has to continue.
      for (const offsetX of [-data.width, 0, data.width]) {
        if (offsetX + data.width < left || offsetX > right) continue;

        ctx.save();
        ctx.translate(width / 2, height / 2);
        ctx.scale(scale, scale);
        ctx.translate(-camera.x + offsetX, -camera.y);
        ctx.lineWidth = 1 / scale;

        // Base pass: stroke only. Filling 199 polygons cost a third of the map
        // budget for a 0.04-alpha wash that is invisible in practice, so the
        // fill is now reserved for the two highlighted countries.
        ctx.strokeStyle = "rgba(222,245,255,0.28)";
        for (const shape of shapes) {
          const [x0, y0, x1, y1] = shape.box;
          if (x1 + offsetX < left || x0 + offsetX > right || y1 < top || y0 > bottom) continue;
          // Sub-pixel islands and microstates: skip rather than rasterise.
          if (x1 - x0 < minSpan && y1 - y0 < minSpan) continue;
          if (highlight.has(shape.id)) continue;
          ctx.stroke(shape.path);
        }

        // Highlighted pass: origin and destination only.
        for (const shape of shapes) {
          if (!highlight.has(shape.id)) continue;
          const [x0, y0, x1, y1] = shape.box;
          if (x1 + offsetX < left || x0 + offsetX > right || y1 < top || y0 > bottom) continue;
          ctx.fillStyle = "rgba(216,184,0,0.14)";
          ctx.fill(shape.path);
          ctx.strokeStyle = "rgba(216,184,0,0.75)";
          ctx.lineWidth = 1.4 / scale;
          ctx.stroke(shape.path);
        }

        ctx.restore();
      }
    };

    const drawRoute = (v: Voyage, progress: number, alpha: number) => {
      const count = tier.routeSamples;
      for (let i = 0; i <= count; i += 1) {
        screenPoints[i * 2] = screenX(v.samples[i * 2]);
        screenPoints[i * 2 + 1] = screenY(v.samples[i * 2 + 1]);
      }

      if (tier.laneUnderlay) {
        ctx.beginPath();
        ctx.moveTo(screenPoints[0], screenPoints[1]);
        for (let i = 1; i <= count; i += 1) ctx.lineTo(screenPoints[i * 2], screenPoints[i * 2 + 1]);
        ctx.setLineDash([]);
        ctx.strokeStyle = `rgba(222,245,255,${0.14 * alpha})`;
        ctx.lineWidth = 1;
        ctx.stroke();
      }

      const upto = Math.max(1, Math.floor(progress * count));
      ctx.beginPath();
      ctx.moveTo(screenPoints[0], screenPoints[1]);
      for (let i = 1; i <= upto; i += 1) ctx.lineTo(screenPoints[i * 2], screenPoints[i * 2 + 1]);
      ctx.setLineDash([2, 7]);
      ctx.lineCap = "round";
      ctx.strokeStyle = `rgba(216,184,0,${0.95 * alpha})`;
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.setLineDash([]);
    };

    const drawPort = (port: Port, x: number, y: number, time: number, alpha: number) => {
      const sx = screenX(x);
      const sy = screenY(y);
      if (sx < -80 || sx > width + 220 || sy < -60 || sy > height + 60) return;

      const pulse = 0.5 + 0.5 * Math.sin(time / 620);

      ctx.globalAlpha = alpha * (0.18 + 0.22 * pulse);
      ctx.fillStyle = "#d8b800";
      ctx.beginPath();
      ctx.arc(sx, sy, 5 + 9 * pulse, 0, Math.PI * 2);
      ctx.fill();

      ctx.globalAlpha = alpha;
      ctx.beginPath();
      ctx.arc(sx, sy, 3.2, 0, Math.PI * 2);
      ctx.fill();

      ctx.font = LABEL_FONT;
      ctx.fillStyle = "rgba(222,245,255,0.85)";
      ctx.textAlign = "left";
      ctx.fillText(port.label, sx + 12, sy + 4);
      ctx.globalAlpha = 1;
    };

    const drawShip = (x: number, y: number, heading: number, alpha: number) => {
      const goingRight = Math.cos(heading) >= 0;
      const mirrored = SHIP_FACES_LEFT ? goingRight : !goingRight;
      let tilt = goingRight ? heading : heading + Math.PI;
      tilt = Math.atan2(Math.sin(tilt), Math.cos(tilt));
      tilt = Math.max(-MAX_TILT, Math.min(MAX_TILT, tilt));

      const scale = SHIP_SCREEN_SIZE / SHIP_VIEWBOX;
      const paint = (fill: string, a: number) => {
        ctx.save();
        ctx.translate(x, y);
        ctx.rotate(tilt);
        ctx.scale(mirrored ? -scale : scale, scale);
        ctx.translate(-SHIP_VIEWBOX / 2, -SHIP_VIEWBOX / 2);
        ctx.globalAlpha = a;
        ctx.fillStyle = fill;
        ctx.fill(shipPath);
        ctx.restore();
      };

      if (tier.glow) paint("#d8b800", alpha * 0.25);
      paint("#f2d02a", alpha);
      ctx.globalAlpha = 1;
    };

    const drawCheck = (x: number, y: number, pop: number, alpha: number) => {
      const radius = 15 * pop;
      const cy = y - 34;

      ctx.globalAlpha = alpha;
      ctx.beginPath();
      ctx.arc(x, cy, radius, 0, Math.PI * 2);
      ctx.fillStyle = "#d8b800";
      ctx.fill();

      if (tier.glow) {
        ctx.globalAlpha = alpha * 0.25;
        ctx.beginPath();
        ctx.arc(x, cy, radius * 1.7, 0, Math.PI * 2);
        ctx.fill();
      }

      ctx.globalAlpha = alpha;
      ctx.beginPath();
      ctx.moveTo(x - 6.5 * pop, cy);
      ctx.lineTo(x - 1.5 * pop, cy + 5 * pop);
      ctx.lineTo(x + 7 * pop, cy - 5.5 * pop);
      ctx.strokeStyle = "#001238";
      ctx.lineWidth = 2.6 * pop;
      ctx.lineCap = "round";
      ctx.lineJoin = "round";
      ctx.stroke();
      ctx.globalAlpha = 1;
    };

    const render = (now: number) => {
      ctx.clearRect(0, 0, width, height);
      if (!map || !voyage) return;

      const elapsed = now - voyage.startedAt;
      const approachMs = voyage.cameraFrom ? PHASE.approach : 0;
      const total = approachMs + PHASE.focus + voyage.travelMs + PHASE.arrive + PHASE.clear;

      let travelT = 0;
      let shipAlpha = 0;
      let checkPop = 0;
      let routeAlpha = 1;
      let targetX = voyage.a.x;
      let targetY = voyage.a.y;
      let targetZoom = ZOOM_NEAR;

      if (elapsed < approachMs) {
        const t = elapsed / approachMs;
        const e = easeInOut(t);
        const origin = voyage.cameraFrom!;
        targetX = origin.x + (voyage.a.x - origin.x) * e;
        targetY = origin.y + (voyage.a.y - origin.y) * e;
        targetZoom = ZOOM_NEAR + (ZOOM_WIDE - ZOOM_NEAR) * Math.sin(Math.PI * t);
        routeAlpha = t;
      } else if (elapsed < approachMs + PHASE.focus) {
        const t = (elapsed - approachMs) / PHASE.focus;
        shipAlpha = Math.max(0, (t - 0.45) / 0.55);
      } else if (elapsed < approachMs + PHASE.focus + voyage.travelMs) {
        const t = (elapsed - approachMs - PHASE.focus) / voyage.travelMs;
        travelT = easeInOut(t);
        shipAlpha = 1;
        targetX = bezierX(voyage, travelT);
        targetY = bezierY(voyage, travelT);
        targetZoom = ZOOM_NEAR + (ZOOM_WIDE - ZOOM_NEAR) * Math.sin(Math.PI * t);
      } else if (elapsed < approachMs + PHASE.focus + voyage.travelMs + PHASE.arrive) {
        const t = (elapsed - approachMs - PHASE.focus - voyage.travelMs) / PHASE.arrive;
        travelT = 1;
        shipAlpha = 1;
        checkPop = easeOutBack(Math.min(1, t / 0.45));
        targetX = voyage.b.x;
        targetY = voyage.b.y;
      } else {
        const t = (elapsed - approachMs - PHASE.focus - voyage.travelMs - PHASE.arrive) / PHASE.clear;
        travelT = 1;
        shipAlpha = 1 - t;
        checkPop = 1;
        routeAlpha = 1 - t * 0.6;
        targetX = voyage.b.x;
        targetY = voyage.b.y;
      }

      if (!cameraInitialised) {
        camera.x = targetX;
        camera.y = targetY;
        camera.zoom = targetZoom;
        cameraInitialised = true;
      } else {
        // Frame-rate independent smoothing. A fixed per-frame factor makes the
        // camera lag proportional to frame duration, so the ship drifts further
        // off-centre on a slow device than a fast one; solving the exponential
        // against real elapsed time keeps the follow identical at any rate.
        const dt = lastFrame ? Math.min(64, now - lastFrame) : 16;
        const k = 1 - Math.exp(-dt / CAMERA_TAU);
        camera.x += (targetX - camera.x) * k;
        camera.y += (targetY - camera.y) * k;
        camera.zoom += (targetZoom - camera.zoom) * k;
      }
      lastFrame = now;

      mapAlpha = Math.min(1, mapAlpha + 0.02);
      ctx.globalAlpha = mapAlpha;
      drawMap(voyage.highlight);
      ctx.globalAlpha = 1;

      const fade = mapAlpha * routeAlpha;
      drawRoute(voyage, travelT, fade);
      drawPort(voyage.from, voyage.a.x, voyage.a.y, now, fade * 0.9);
      drawPort(voyage.to, voyage.b.x, voyage.b.y, now, fade * (travelT > 0.6 ? 0.9 : 0.35));

      if (shipAlpha > 0) {
        const clamped = Math.min(0.999, Math.max(0.001, travelT));
        const sx = screenX(bezierX(voyage, travelT));
        const sy = screenY(bezierY(voyage, travelT));
        drawShip(sx, sy, bezierHeading(voyage, clamped), shipAlpha * fade);
        if (checkPop > 0) drawCheck(sx, sy, checkPop, shipAlpha * fade);
      }

      if (elapsed >= total) voyage = makeVoyage(now, voyage.to);
    };

    const loop = (now: number) => {
      frame = requestAnimationFrame(loop);
      // Pace to the tier's target rate. Below 60 Hz this is the cheapest win
      // available: half the frames is half the work, and the easing curves are
      // slow enough that 30 fps reads as smooth.
      if (now - lastDraw < frameInterval - 1) return;
      lastDraw = now;
      render(now);
    };

    const start = () => {
      if (running || reducedMotion || !map) return;
      running = true;
      frame = requestAnimationFrame(loop);
    };

    const stop = () => {
      running = false;
      if (frame) cancelAnimationFrame(frame);
      frame = 0;
    };

    const renderStatic = () => {
      if (!map) return;
      voyage = makeVoyage(0);
      mapAlpha = 1;
      camera.x = (voyage.a.x + voyage.b.x) / 2;
      camera.y = (voyage.a.y + voyage.b.y) / 2;
      camera.zoom = ZOOM_WIDE;
      cameraInitialised = true;

      ctx.clearRect(0, 0, width, height);
      drawMap(voyage.highlight);
      drawRoute(voyage, 1, 1);
      drawPort(voyage.from, voyage.a.x, voyage.a.y, 0, 0.9);
      drawPort(voyage.to, voyage.b.x, voyage.b.y, 0, 0.9);
      const sx = screenX(voyage.b.x);
      const sy = screenY(voyage.b.y);
      drawShip(sx, sy, bezierHeading(voyage, 0.999), 1);
      drawCheck(sx, sy, 1, 1);
    };

    const onVisibility = () => {
      if (document.hidden) stop();
      else if (onScreen) start();
    };

    resize();

    fetch("/world-map.json")
      .then((response) => (response.ok ? response.json() : null))
      .then((data: WorldMapData | null) => {
        if (cancelled || !data) return;
        shapes = data.countries.map((country) => ({
          id: country.id,
          path: new Path2D(country.d),
          box: country.box,
        }));
        // Keep only the projection metadata. Dropping the parsed country list
        // releases ~139 KB of path strings once the Path2D objects own the
        // geometry, and it is never read again.
        map = { width: data.width, height: data.height, geo: data.geo, countries: [] };
        baseScale = Math.max(width / data.width, height / data.height);
        voyage = makeVoyage(performance.now());

        if (reducedMotion) renderStatic();
        else if (onScreen && !document.hidden) start();
      })
      .catch(() => {
        // Non-fatal: the hero simply keeps its plain navy background.
      });

    const resizeObserver = new ResizeObserver(() => {
      resize();
      if (reducedMotion) renderStatic();
    });
    resizeObserver.observe(canvas);

    const intersectionObserver = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting;
        if (onScreen && !document.hidden) start();
        else stop();
      },
      { threshold: 0 }
    );
    intersectionObserver.observe(canvas);
    document.addEventListener("visibilitychange", onVisibility);

    return () => {
      cancelled = true;
      stop();
      resizeObserver.disconnect();
      intersectionObserver.disconnect();
      document.removeEventListener("visibilitychange", onVisibility);
      // Release the geometry; a 199-entry Path2D set is not small.
      shapes = [];
      map = null;
      voyage = null;
    };
  }, [coarsePointer, reducedMotion]);

  return (
    <canvas
      ref={canvasRef}
      aria-hidden="true"
      className={`pointer-events-none select-none ${className}`}
    />
  );
}
